// Liste des expressions à faire deviner. Ajoutez simplement une ligne pour en ajouter une.
window.POLYCEA_WORDS = [
  "Dominique",
  "Marcel",
  "Alexis",
  "Charlotte",
  "Jeffani",
  "Martin",
  "SNCF",
  "Canal+",
  "Oneflex",
  "Coviflex",
  "Polyconseil",
  "Poissonnière",
  "R+2",
  "R-3",
  "Pacifique",
  "Dragonnet",
  "Bureau de Dom",
  "Blue",
  "Daurade",
  "Axa Climate",
  "Antai",
  "Henri",
  "Adrien Vinay",
  "Data",
  "Dev",
  "PM",
  "Alivia",
  "PowerPoint",
  "Ulysse",
  "Berri",
  "Christian",
  "Reselin",
  "Anaïs",
  "Polypoint",
  "Séminaire",
  "Accolades",
  "Vert",
  "Ping pong",
  "Miracle gabonnais",
  "Lucca",
  "Grands Boulevards",
  "Bonne nouvelle",
  "Grand Rex",
  "Soirée de noel",
  "Nibelis",
  "Jenji",
  "Slack",
  "#random",
  "Polytechnique",
  "Gallica",
  "rue Rougemont",
  "Local vélo",
  "Embiez",
  "Caraibes",
  "Caspienne",
  "Egee",
  "Indien",
  "Méditerranée",
  "Espadon",
  "We make innovation happen... for real",
  "Bolloré",
  "Hachette",
  "Autolib",
  "Une bulle",
  "Pirates",
  "Nirio",
  "Pass Culture",
  "Arianegroup",
  "TeFPS",
  "Fourrière",
  "MBDA",
  "Shadox",
  "eovia",
  "ChooseMyCompany",
  "Expertise",
  "Marc",
  "35 ans",
  "Frédéric",
  "Clément",
  "Fatine",
  "Stefano",
  "Véronique",
  "Machine à café",
  "Musée des arts et métiers",
  "Raid Centrale Supelec",
  "Polycomdor",
  "Polybrairie",
  "Escalade",
  "Polypadel",
  "Polyjeux",
  "Spikeball",
  "Tournoi de ping pong",
  "Bruno",
  "Polystyrène",
  "Pongo",
  "Polyweek for good",
  "Polypot",
  "Bar à jeux",
  "Sushi",
  "Turbot",
];
