// Liste des expressions à faire deviner. Ajoutez simplement une ligne pour en ajouter une.
window.POLYCEA_WORDS = [
  "Dominique",
  "Marcel",
  "Alexis",
  "Charlotte",
  "Jeffani",
  "Martin",
  "SNCF",
  "Canal+",
  "Oneflex",
  "Coviflex",
  "Polyconseil",
  "Poissonnière",
  "R+2",
  "R-3",
  "Pacifique",
  "Dragonnet",
  "Bureau de Dom",
  "Blue",
  "Daurade",
  "Axa Climate",
  "Antai",
  "Henri",
  "Adrien Vinay",
  "Data",
  "Dev",
  "PM",
  "Alivia",
  "PowerPoint",
  "Ulysse",
  "Berri",
  "Christian",
  "Reselin",
  "Anaïs",
  "Polypoint",
  "Séminaire",
  "Accolades",
  "Vert",
  "Ping pong",
  "Miracle gabonnais",
  "Lucca",
  "Grands Boulevards",
  "Bonne nouvelle",
  "Grand Rex",
  "Soirée de noel",
  "Nibelis",
  "Jenji",
  "Slack",
  "#random",
];
